# apple-app-site-association 서빙
location /.well-known/apple-app-site-association {
    default_type application/json;
    alias /etc/nginx/aasa/apple-app-site-association.json;
}

location /.well-known/assetlinks.json {
    default_type application/json;
    alias /etc/nginx/aasa/assetlinks.json;
}
